### ISSUE TITLE
Dont allow media embed in signatures

### ISSUE THREAD

**Issue by VSEphpbb** [phpbb-extensions/mediaembed#11]
Don't allow users to post embedded media in signatures

**Comment by VSEphpbb** [comment]
@JoshyPHP Can you please help us figure this one out? Is there a way to disable MediaEmbed when posting a signature?

The last thing many forum admins want is users putting videos into their sigs 😕

**Comment by JoshyPHP** [comment]
You can toggle the MediaEmbed plugin with [`disablePlugin('MediaEmbed')`](http://s9e.github.io/TextFormatter/api/s9e/TextFormatter/Parser.html#method_disablePlugin). The `textformatter.s9e.parser` service has a `get_parser()` method to retrieve the instance.

I don't know where in phpBB you should call that though. I see that some events have a `mode` variable, it's probably what you'll have to use to toggle the plugin depending on the mode.

**Comment by VSEphpbb** [comment]
@JoshyPHP Thanks. It looks like we can use just `parser->disableTag('MEDIA')` as the only relevant BBCode (we don't enable individual BBCodes).

**Comment by VSEphpbb** [comment]
Hmm, that does stop it from being "posted", but it still gets rendered if the signature containes a link anyways :/

**Comment by VSEphpbb** [comment]
@JoshyPHP side note: mind releasing TextFormatter 0.8 this weekend? Thx.

**Comment by rxu** [comment]
@JoshyPHP 
```php
'core.text_formatter_s9e_parse_before'		=> 'configure_parser',
```
```php
	public function configure_parser($event)
	{
		/** @var \TextFormatter\s9e\parser $parser */
		$parser = $event['parser'];
		$parser->disable_bbcode('media');
		$event['parser'] = $parser;
	}
```
With this, phpBB throws warning when you try saving the sig containing any plain text URL with the protocol (http:// or https:// f.e.).
If you restrict individual BBCode, like```$parser->disable_bbcode('youtube');``` f.e., it works ok (doesn't allow youtube URLs but allows all the rest plain text URLs).
Why is that?

**Comment by VSEphpbb** [comment]
@rxu you don't need to pass the parser back to the event.

Just do:
```php
$service = $event['parser'];
$parser = $service->get_parser();
$parser->disable_bbcode('MEDIA');
```

**Comment by JoshyPHP** [comment]
@rxu I don't know. What does the warning say?

@VSEphpbb As I recall, `$event['parser']` will contain the parser service, which provides the `disable_bbcode()` method.

I'll look into publishing 0.8.0 tomorrow.

**Comment by rxu** [comment]
@JoshyPHP That's just usual phoBB warning ```You can't use certain BBCodes: [media]```.

**Comment by VSEphpbb** [comment]
@JoshyPHP & @rxu 
So a couple observations now...It's sorta working, and sorta not.

With this code:
```
$service = $event['parser'];
$parser = $service->get_parser();
$parser->disablePlugin('MediaEmbed');
$service->disable_bbcode('youtube');
```
In this scenario, If you post a link in the `[media]` bbcode you get an error:
**"You cannot use certain BBCodes: [youtube]."** The error is a little misleading but at least there's an error.

Worse, though, if you post a raw link, at first it seems to work, but after a couple page loads, the link is eventually converted into an embedded youtube video file on the post pages.

Alternatively, doing this (disabling the media bbcode):
```php
$service = $event['parser'];
$service->disable_bbcode('MEDIA');
```
This makes it impossible to post a media link, whether it's in a media tag or raw (and the error message is a little more correct). With the error **You cannot use certain BBCodes: [media].**

However, you also get the error message if you just post a top level domain link to a supported site, i.e.: `http://www.youtube.com` In fact, it also gives you an error if your link is in any other BBCode, like the URL bbcode.

So it's like every solution tried so far adds new problems :/

**Comment by rxu** [comment]
With the latter case it will actually disable any link (not just for supported sites), f.e. ```https://www.phpbb.com```.

**Comment by rxu** [comment]
The error comes from here https://github.com/phpbb/phpbb/blob/master/phpBB/phpbb/textformatter/s9e/parser.php#L220-L224
``php
			else if ($msg === 'Tag is disabled')
			{
				$name = strtolower($context['tag']->getName());
				$errors[] = array('UNAUTHORISED_BBCODE', '[' . $name . ']');
			}
```

The question is why the parser considers URLs disabled together with disabling the ```MEDIA``` tag.

**Comment by JoshyPHP** [comment]
@rxu If you call `disablePlugin('MediaEmbed')` and `disableTag('MEDIA')` on the parser instance you should be able to post links normally and if you use `[media]` then you should get the expected error message.

**Comment by rxu** [comment]
So, is it impossible to just disable tag without disabling the whole plugin?

**Comment by JoshyPHP** [comment]
All the plugin does (at parsing time) is put invisible `MEDIA` tags around URLs. If you disable the plugin you get no implicit `MEDIA` tags and no errors for posting links. It doesn't prevent users from using `[media]` as a BBCode, because BBCodes are handled by the BBCodes plugin. That's why you need to disable both.

**Comment by rxu** [comment]
Oh. Should it really wrap all URLs with the MEDIA tag but not only those from supported site ids?

**Comment by JoshyPHP** [comment]
Yes, so that both raw URLs and `[media]` share the same code path as early as possible. The plugin doesn't inspect URLs, that's done by the `MEDIA` tag's configuration. That's why you can still use `[media]` when the MediaEmbed plugin is disabled but you can't use either when `MEDIA` is disabled.

Plugins only handle the markup side of things; They are akin to lexers, although each plugin is different and may take on more or less responsibility. Same thing with `[url]`, URLs in plain text and Markdown links. Plugins mark a portion of text to be handled by the `URL` tag's configuration and then whatever validates URLs takes it from there.

**Comment by VSEphpbb** [comment]
@JoshyPHP 
> If you call disablePlugin('MediaEmbed') and disableTag('MEDIA')

When we do that, everything seems OK at first. But after a few page loads, a raw link eventually gets turned back into embedded video. (Maybe the reparser is interfering?)

Using this strategy:
```php
$service = $event['parser'];
$parser = $service->get_parser();
$parser->disablePlugin('MediaEmbed');
$parser->disableTag('MEDIA');
$service->disable_bbcode('youtube');
```

At first what gets stored in the DB looks like:
```
<r><URL url="http://www.youtube.com/watch?v=sP4NMoJcFd4">http://www.youtube.com/watch?v=sP4NMoJcFd4</URL></r>
```

But after a few page views, the signature is automatically converted to:
```
<r><YOUTUBE id="sP4NMoJcFd4" url="http://www.youtube.com/watch?v=sP4NMoJcFd4">http://www.youtube.com/watch?v=sP4NMoJcFd4</YOUTUBE></r>
```

**Comment by JoshyPHP** [comment]
Yeah, I can't explain that phenomenon apart from the reparser doing its thing. It's not supposed to reparse everything all the time though so there may be an issue there.

**Comment by rxu** [comment]
@JoshyPHP That is because the text reparser cron job never stops reparsing posts (and it reparses even already reparsed ones all the time),

**Comment by VSEphpbb** [comment]
I thought the reparser was only really supposed to run once?? That is, to update boards after a 3.1 to 3.2 update. Seems like a problem if it's always on. 

Certainly would allow us to help solve this issue here if it wasn't always running.

**Comment by rxu** [comment]
The ticket: https://tracker.phpbb.com/browse/PHPBB3-14814
