### ISSUE TITLE
running 3.2, extension won't install

### ISSUE THREAD

**Issue by raafirivero** [phpbb-extensions/mediaembed#28]
runing phpbb 3.2 and PHP 5.6 but when I try to enable it says to please verify the extension's requirements. My site satisfies the only two listed requirements...

**Comment by VSEphpbb** [comment]
Then you have the old other mediaembed extension installed.

**Comment by raafirivero** [comment]
uninstalled the other extension and now this one gives a PHP error when attempting to install it. It's  looking for a file in the s9e directory, which is deleted.

**Comment by VSEphpbb** [comment]
What file. You shouldn't delete anything (except extensions)

**Comment by raafirivero** [comment]
- with the s9e/mediaembed extension installed but disabled, this newer mediaembed extension cannot be enabled ("please verify the extension's requirements").
- with the s9e/mediaembed extension disabled and removed from the filesystem, I get the attached error in attempting to enable phpbb Media Embed 
` in file [ROOT]/phpbb/class_loader.php on line 160: require([ROOT]/ext/s9e/mediaembed/ext.php): failed to open stream: No such file or directory`

<img width="634" alt="screen shot 2017-01-31 at 11 47 51 am" src="https://cloud.githubusercontent.com/assets/6245124/22474890/4e4dbdf8-e7ab-11e6-878a-819aa02c8480.png">

**Comment by VSEphpbb** [comment]
clear your cache

**Comment by raafirivero** [comment]
Beautiful, thank you.
