### ISSUE TITLE
Allow users to disable the extension in UCP

### ISSUE THREAD

**Issue by C1n** [phpbb-extensions/mediaembed#34]
Feature request: to allow users to disable / enable the extension in their UCP.

**Comment by rxu** [comment]
The only place where extensions can be enabled or disabled is ACP. That's not going to bt changed ever.
Please elaborate what do you mean in details.

**Comment by VSEphpbb** [comment]
There are no plans to do this as we see that as taking a step backwards. Likewise, it's not apparent to us if that's even possible as the functionaity is not detrmined on a per user basis.

**Comment by C1n** [comment]
I don't agree with the premise that this is taking a step backwards. I'm just asking if it is possible to allow users to disable the automatic embedding if they choose so, just like phpBB now offers the option to users to disable bbcodes or smilies. However I do understand the technical difficulties as the functionality is not determined on a per user basis.
