### ISSUE TITLE
Can't upgrade to latest version

### ISSUE THREAD

**Issue by eremini** [phpbb-extensions/mediaembed#44]
Hello,

While trying to enable version 1.0.2 after update I get the following error:

Something went wrong during the request and an exception was thrown. The changes made before the error occurred were reversed to the best of our abilities, but you should check the board for errors.

The group "REGISTERED_COPPA" unexpectedly does not exist.

Please advise.

**Comment by VSEphpbb** [comment]
You have deleted usergroups are part of phpBB. Please visit phpBB's forums and search them for solutions to resolve that issue.
