### ISSUE TITLE
Add option to use youtube-nocookie instead of standard youtube

### ISSUE THREAD

**Issue by Crizz0** [phpbb-extensions/mediaembed#80]
This would help people, who want to use this extension following the GDPR

**Comment by iMattPro** [comment]
Talk to S9E

**Comment by JoshyPHP** [comment]
Assuming you're referring to me in a weird roundabout way, I have no immediate plans to make the hostname used in the default YouTube embed configurable. I recommend doing the same thing I do in the XenForo add-on I maintain, and simply replace the hostname: https://github.com/s9e/xenforo-ext-media-sites/blob/f4f668a91d8b2224fc4e3a1c7f81e96cea410bca/addon/_data/template_modifications.xml#L48-L51
